### ISSUE TITLE
Enhanced networking role removed for later xenial AMIs

### ISSUE THREAD

**Issue by sihil** [guardian/amigo#153]
The enhanced-networking role doesn't work on the latest Xenial AMIs due to a bug in the driver. However the later Xenial AMIs also include a late enough version of the driver that we no longer need to roll it ourselves.

I suggest that enhanced-networking is taken out of ubuntu-init and included explicitly where needed.

**Comment by mchv** [comment]
👍

**Comment by sihil** [comment]
Turns out that this isn't true. It was claimed on a website, but I couldn't verify it.

I'm going to close this for now.
