### ISSUE TITLE
Add more tags to AMIs

### ISSUE THREAD

**Issue by cb372** [guardian/amigo#7]
AMIs should be tagged with information about what features they contain.

* One tag per feature? Is there a limit to the number of tags you can add?
* Include info about custom variables passed to the role?

Should talk to @sihil and @adamnfish to decide on a format for tags that both Riff Raff and AMIable understand.

Should also add the AMIgo recipe ID as a tag.

**Comment by adamnfish** [comment]
Yes please! Let's chat IRL.

**Comment by cb372** [comment]
Talked to Adam and decide the recipe ID and build number are enough for AMIable.

**Comment by adamnfish** [comment]
(Also needs to tag amigo as the creator, but yes - great!)

**Comment by sihil** [comment]
Can we add a tag containing a URL to the AmiGo build permalink? Plausible?

**Comment by adamnfish** [comment]
Would build number not be enough to uniquely identify a build in amigo, without e.g. coupling the tags to the hostname?
