### ISSUE TITLE
Finish implementing the UI

### ISSUE THREAD

**Issue by cb372** [guardian/amigo#8]
This is boring, but I can't put it off forever...

We still need the following pages:

* `/base-images/:id` - display detailed info about a base image
* `/base-images/:id/edit` - form to update a base image
* `/base-images/new` - form to create a base image
* `/roles/:id` - display info extracted from the role's files. Render README.md if there is one available. Display any variables that the role accepts, along with their default values.
* `/recipes/:id` - display detailed info about the recipe at top of page. Underneath, show a list of recently completed or running bakes, linking to the corresponding bake pages. Put a big Bake! button somewhere on the page.
* `/recipes/:id/edit` - form to update a recipe
* `/recipes/new` - form to create a recipe
* `/bake/:id` - show logs for a bake. Updates in real time using SSE.

**Comment by adamnfish** [comment]
You could offload some of this to AMIable (I'm looking at AMI info)
